Added Projectile and ProjectileTest
ElkySchles/schlesinger-mco152-projectile pull request #1
Opened 2023-02-02 01:46 UTC by ElkySchles

2023-02-02 04:45 UTC, andrewoid commented on src/Weiss/projectile/Main.java
> +package Weiss.projectile;
Package names should be in lower case

2023-02-02 04:45 UTC, andrewoid commented on src/Weiss/projectile/Projectile.java
> +    public Projectile(double angle, double velocity, double time)
Time does not need to be passed in it will always start at 0

2023-02-02 04:45 UTC, andrewoid commented on src/Weiss/projectile/Projectile.java
> +    public double getY(double delta)
The time is internal to Projectile. You don't need delta

2023-02-02 04:45 UTC, andrewoid commented on src/Weiss/projectile/Main.java
> +    public static void main(String[] args){
Run "Reformat Code"

2023-02-07 15:46 UTC, ElkySchles commented
Hi Professor,
When I try to rename my package name and make it lower case, it doesn't
change. It still stays upper. I don't know how to correct it.
Do you have any tips?

On Wed, Feb 1, 2023 at 11:45 PM Andrew Schwimmer ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/Weiss/projectile/Main.java
> <https://github.com/ElkySchles/schlesinger-mco152-projectile/pull/1#discussion_r1094009353>
> :
>
> > @@ -0,0 +1,17 @@
> +package Weiss.projectile;
>
> Package names should be in lower case
> ------------------------------
>
> In src/Weiss/projectile/Projectile.java
> <https://github.com/ElkySchles/schlesinger-mco152-projectile/pull/1#discussion_r1094009794>
> :
>
> > @@ -0,0 +1,45 @@
> +package Weiss.projectile;
> +
> +public class Projectile {
> +    private final double angle;
> +    private final double velocity;
> +    public double time;
> +
> +
> +    public Projectile(double angle, double velocity, double time)
>
> Time does not need to be passed in it will always start at 0
> ------------------------------
>
> In src/Weiss/projectile/Projectile.java
> <https://github.com/ElkySchles/schlesinger-mco152-projectile/pull/1#discussion_r1094010293>
> :
>
> > +    }
> +    public void incTime(double delta){
> +        time += delta;
> +    }
> +    public double getTime(){
> +        return time;
> +    }
> +    public double getAngle()
> +    {
> +        return angle;
> +    }
> +    public double getVelocity()
> +    {
> +        return velocity;
> +    }
> +    public double getY(double delta)
>
> The time is internal to Projectile. You don't need delta
> ------------------------------
>
> In src/Weiss/projectile/Main.java
> <https://github.com/ElkySchles/schlesinger-mco152-projectile/pull/1#discussion_r1094010751>
> :
>
> > @@ -0,0 +1,17 @@
> +package Weiss.projectile;
> +public class Main {
> +    public static void main(String[] args){
>
> Run "Reformat Code"
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ElkySchles/schlesinger-mco152-projectile/pull/1#pullrequestreview-1280330009>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZ6KJCHGE2AGPFKKTTG6MO3WVM3VRANCNFSM6AAAAAAUONYFZ4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2023-02-07 18:29 UTC, andrewoid requested changes

2023-02-07 18:29 UTC, andrewoid commented on src/Weiss/projectile/Projectile.java
> +        this.time = time;
This line doesn't do anything.
I'm fairly sure that it shows up as a warning as well.

2023-02-07 18:29 UTC, andrewoid commented on src/Weiss/projectile/Projectile.java
> +        return Math.sin(Math.toRadians(angle)) * velocity * getTime() - .5 * 9.8 * Math.pow(getTime(), 2);
instead of `Math.pow(getTime(), 2)` you should just do `time * time`

2023-02-07 18:29 UTC, andrewoid commented on src/Weiss/projectile/Projectile.java
> +        return Math.cos(Math.toRadians(angle)) * velocity * getTime();
just use `time` instead of calling `getTime()`

2023-02-07 18:29 UTC, andrewoid commented on src/Weiss/projectile/ProjectileTest.java
> +class ProjectileTest {
I'm pretty sure these tests fail now.

2023-02-09 00:40 UTC, andrewoid commented on src/Weiss/projectile/ProjectileTest.java
> +        assertEquals(299.2011951609338, projectile.getX(), actual);
`assertEquals(299.2011, projectile.getX(), 0.0001);`

2023-02-09 00:41 UTC, andrewoid commented on src/Weiss/projectile/Projectile.java
> +        return delta;
make this a void

2023-02-09 00:58 UTC, andrewoid approved these changes

2023-02-09 00:59 UTC, merged